sudo: false

language: elm
elm:
  - elm0.19.0

git:
  depth: false

if: branch = master

stages:
- Build 🔨

jobs:
  include:
    - stage: Build 🔨
      script:
      - FORMAT=$(elm-format --validate src/ test/)
      - test "$FORMAT" = "[]" || (echo $FORMAT && exit 1)

    - stage: Build 🔨
      script:
      - elm make --optimize
